### ISSUE TITLE
pimatic crashes if rss-server is not reachable

### ISSUE THREAD

**Issue by treban** [saxn-paule/pimatic-tv-program#1]
```
08:09:30.933 [pimatic] An uncaught exception occurred: Error: getaddrinfo EAI_AGAIN www.tvspielfilm.de:80
08:09:30.933 [pimatic]>    at Object.exports._errnoException (util.js:870:11)
08:09:30.933 [pimatic]>    at errnoException (dns.js:31:15)
08:09:30.933 [pimatic]>    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:77:26)
08:09:30.933 [pimatic]>From connect
08:09:30.933 [pimatic]>    at Socket.connect (/opt/pimatic-dev/node_modules/pimatic/startup.coffee:55:29)
08:09:30.933 [pimatic]>    at Agent.exports.connect.exports.createConnection (net.js:63:26)
08:09:30.933 [pimatic]>    at Agent.createSocket (_http_agent.js:172:16)
08:09:30.933 [pimatic]>    at Agent.addRequest (_http_agent.js:141:23)
08:09:30.933 [pimatic]>    at new ClientRequest (_http_client.js:132:16)
08:09:30.933 [pimatic]>    at Object.exports.request (http.js:31:10)
08:09:30.933 [pimatic]>    at Request.start (/opt/pimatic-dev/node_modules/pimatic-tv-program/node_modules/request/request.js:748:32)
08:09:30.933 [pimatic]>    at Request.end (/opt/pimatic-dev/node_modules/pimatic-tv-program/node_modules/request/request.js:1512:10)
08:09:30.933 [pimatic]>    at end (/opt/pimatic-dev/node_modules/pimatic-tv-program/node_modules/request/request.js:561:14)
08:09:30.933 [pimatic]>    at Immediate._onImmediate (/opt/pimatic-dev/node_modules/pimatic-tv-program/node_modules/request/request.js:575:7)
08:09:30.933 [pimatic]>    at processImmediate [as _immediateCallback] (timers.js:383:17)
08:09:30.933 [pimatic]> This is most probably a bug in pimatic or in a module, please report it!
08:09:30.934 [pimatic] shutting pimatic down...
```

**Comment by saxn-paule** [comment]
**version 0.0.5** *released 2017-11-27*
* avoid pimatic to crash on connection error
* fixed responsive design

Please retest

**Comment by treban** [comment]
bug is gone
